### ISSUE TITLE
IE11 Problem on Creditcard Registration

### ISSUE THREAD

**Issue by bizarrochris** [Mangopay/cardregistration-js-kit#43]
Hi,

after communication with the support, I was asked to create an issue here:

We are experiencing problems on Mangopay Card Registration in IE 11.

Here is the steps from the network tab in the dev tools:

Cardregistration:
`{"id":"33980615","url":"https://homologation-webpayment.payline.com/webpayment/getToken","key":"1X0m87dmM2LiwFgxPLBJ","data":"HBalUf7sKsj1NiktfVS7-1u30-ijxuXfMgs81w3Ru7o9_U-QBr8ktqxG1lt7-96wS4wCy-yiraxeE65tmxOe8A","cardType":"CB_VISA_MASTERCARD"}`

The Get Token Request
(https://homologation-webpayment.payline.com/webpayment/getToken)
```
Pparams:
     accessKeyRef: 1X0m87dmM2LiwFgxPLBJ
     cardCvx: 123
     cardExpirationDate: 0123
     cardNumber: 4706750000000009
     data:
HBalUf7sKsj1NiktfVS7-1u30-ijxuXfMgs81w3Ru7o9_U-QBr8ktqxG1lt7-96wS4wCy-yiraxeE65tmxOe8A

```
returns:
`data=nyE9OPhlGammVS88Gn2dO3JSFGU_-feXaoa2OQ7YEmpSBGx8LTSkPlZnyCNqsGv2t0OhGrxSaDO5DNDwFu7g-qcvOh1IRkLlFV-TAmyWIlSWcz3x1Jp0WXCdNN-XTncy0ftIYwFxOdfmDQ5GtM_cIg`

Then we send the registration:

```
Params:
     Id: 33980615
     RegistrationData:
data%3DnyE9OPhlGammVS88Gn2dO3JSFGU_-feXaoa2OQ7YEmpSBGx8LTSkPlZnyCNqsGv2t0OhGrxSaDO5DNDwFu7g-qcvOh1IRkLlFV-TAmyWIlSWcz3x1Jp0WXCdNN-XTncy0ftIYwFxOdfmDQ5GtM_cIg
```

Returns:
```
{"Message":"the card registration has already been
processed","Type":"cardregistration_already_process","Id":"6cdf5066-f04a-45d9-b2fd-518a2f031969#1506011551","Date":1506011552.0,"errors":null}

```

According to Tikhoze from Support:

This is your log history for that card registration object:
deversports	/cardregistrations	POST	21/09/2017 16:26:17	v2.01	OK	
deversports	/CardRegistrations/33980615	POST	21/09/2017 16:27:08	v2	OK	
deversports	/CardRegistrations/33980615	POST	21/09/2017 16:28:11	v2	BadRequest
deversports	/CardRegistrations/33980615	POST	21/09/2017 16:32:31	v2	BadRequest	

As you can see three POST requests were sent to update the same card registration object. The first successfully created the card.  The successive two failed as the registration had already been processed.

It seems the second request is resent or something - or that an earlier request was cached - and resent.

Here is some possible explanation on stackoverflow: 
https://stackoverflow.com/a/25170531/7347577

The exact same implementation works flawlessly in Chrome and Firefox
